name: Deploy App using Custom Action

on:
  workflow_dispatch:
    inputs:
      heroku_app_name:
        description: 'The name of the Heroku app (optional)'
        required: false
        type: string
      create_new_app:
        description: 'Check this box to create a new Heroku app'
        required: false
        type: boolean
        default: false
      docker_image:
        description: 'The full Docker Hub image name and tag (e.g., your-username/your-image:latest)'
        required: true
        type: string
      heroku_config_vars:
        description: 'Heroku config variables (one per line, e.g., KEY=VALUE)'
        required: false
        type: string

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
        uses: misaya98/docker2heroku@main

        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_image: ${{ github.event.inputs.docker_image }}
          heroku_app_name: ${{ github.event.inputs.heroku_app_name }}
          create_new_app: ${{ github.event.inputs.create_new_app }}
          heroku_config_vars: ${{ github.event.inputs.heroku_config_vars }}

          # (可选) 如果您的 Docker 镜像是私有的，请取消以下行的注释
          # dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          # dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
